name: Sanity Tests

on:
  # Automated Sanity Tests - Run every 2 hours during business hours
  schedule:
    - cron: '0 */2 * * *'

  # Manual trigger
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running tests manually'
        required: false
        default: 'Manual sanity test run'
      base_url:
        description: 'Base URL for the application (optional, overrides secret)'
        required: false

permissions:
  actions: write
  contents: read

jobs:
  run-sanity-tests:
    uses: ./.github/workflows/core-test-runner.yml
    with:
      test_type: 'sanity'
      test_command: 'npm run test:sanity'
      retention_days: '1'
      test_description: 'Sanity Tests'
      cleanup_before_run: 'true'
      timeout_minutes: 60
      test_tags: '@sanity'
      base_url: ${{ inputs.base_url }}
